- RandomSamplingDataPointsFilter:
    prob: 0.25
#- BoundingBoxDataPointsFilter:
#    xMin: -15
#    xMax: 0
#    yMin: -3
#    yMax: 3
#    zMin: -10
#    zMax: 0
#    removeInside: 1
- SurfaceNormalDataPointsFilter:
    knn: 5
    epsilon: 0
    keepNormals: 1
    keepDensities: 1
#- MaxDensityDataPointsFilter:
#     maxDensity: 1000.0
#- SimpleSensorNoiseDataPointsFilter:
#    sensorType: 0
- ObservationDirectionDataPointsFilter
- OrientNormalsDataPointsFilter 
