- SurfaceNormalDataPointsFilter:
    knn: 5
    epsilon: 0
    keepNormals: 1
    keepDensities: 0
- OctreeGridDataPointsFilter:
    buildParallel: 1
    maxPointByNode: 1
    maxSizeByNode: 0.2
    samplingMethod: 3
#- VoxelGridDataPointsFilter:
#    vSizeX: 0.5
#    vSizeY: 0.5
#    vSizeZ: 0.5
#    useCentroid: 1
#    averageExistingDescriptors: 1
# Do not use subsampling filters!
#- MaxDensityDataPointsFilter:
#   maxDensity: 1.0  # 5.0
#- MaxPointCountDataPointsFilter:
#    maxCount: 30000

