- SurfaceNormalDataPointsFilter:
    knn: 5
    epsilon: 0
    keepNormals: 1
    keepDensities: 0
- OctreeGridDataPointsFilter:
    buildParallel: 1
    maxPointByNode: 1
    maxSizeByNode: 0.2
    samplingMethod: 3
- ObservationDirectionDataPointsFilter
- OrientNormalsDataPointsFilter 
